### ISSUE TITLE
Background Transparency

### ISSUE THREAD

**Issue by VJ-Katza** [leadedge/SpoutSlideshow#2]
When syphoning transparency is disabled
Attached a screenshot
https://ibb.co/yX8dfPf

**Comment by leadedge** [comment]
I am not sure of the exact problem and can't reproduce it. Can you give me step-by-step instructions to reproduce.

**Comment by VJ-Katza** [comment]
![TRANSPARENCY](https://user-images.githubusercontent.com/6804884/107483386-abaf0e00-6b89-11eb-83cf-75db16a60f89.jpg)
Thank you leadedge,
1. Use a 1280x720 resolution with "spout Slideshow"
2. Insert an image with different ration (at the example screenshot the moon image is a square 1:1 ratio)
3. Now the extra Left & Right are being sent to the reciever (resolume) as black stripes and not as transparent background,
This is helpful when importing various size images into the slideshow

**Comment by leadedge** [comment]
I tested the release version of SpoutSlideShow and can't reproduce it. Both the picture and the background blend together. Are there any extra settings in Arena that would change this.

![SpoutSlideShowCapture](https://user-images.githubusercontent.com/7351229/107588833-9521b900-6c54-11eb-9576-e7536678e222.JPG)

**Comment by leadedge** [comment]
If I change to Alpha blend in Resolume, the slideshow is half blended and that's enough to make some changes that seem to fix the problems.

You will find the re-built file in the "bin" folder. [Download it directly](https://github.com/leadedge/SpoutSlideshow/raw/master/bin/SpoutSlideshow.exe) and copy to your "bin" folder.

If that works for you I will make another release.

**Comment by VJ-Katza** [comment]
Thanks so much That solved the problem!
![T2](https://user-images.githubusercontent.com/6804884/107608267-23da0a00-6c44-11eb-94bd-e4e08f0a99c5.jpg)

I guess the blending in your screenshot accured because the Video slider was not at Max.
Thanks Again!

**Comment by leadedge** [comment]
OK - if it works for you, I won't even worry about it.

What it was doing was clearing the background to black with full opaque alpha. Now it's full transparent. The hard cut was a simple change. It had been designed to start again like that only because it's clear that it started again! Maybe not so important.

I hope this gets you going with your project.
